/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface FamilyMemberProfile { 'name' : string, 'profileId' : string }
export interface MedicalRecord {
  'data' : string,
  'recordDate' : bigint,
  'recordType' : RecordType,
  'recordId' : string,
}
export type RecordType = { 'CBC' : null } |
  { 'LFT' : null } |
  { 'GeneralAilments' : null } |
  { 'BloodSugar' : null } |
  { 'BloodPressure' : null } |
  { 'Cholesterol' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMedicalRecord' : ActorMethod<
    [string, bigint, RecordType, string, [] | [string]],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createFamilyMember' : ActorMethod<[string], string>,
  'deleteFamilyMember' : ActorMethod<[string], undefined>,
  'deleteMedicalRecord' : ActorMethod<[string, [] | [string]], undefined>,
  'deleteUploadedFile' : ActorMethod<[string, boolean], undefined>,
  'getAllRecords' : ActorMethod<[[] | [string]], Array<MedicalRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMedicalRecord' : ActorMethod<[string, [] | [string]], MedicalRecord>,
  'getRecordsByType' : ActorMethod<
    [RecordType, [] | [string]],
    Array<MedicalRecord>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasMedicalRecordAccess' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listFamilyMembers' : ActorMethod<[], Array<FamilyMemberProfile>>,
  'listUploadedFiles' : ActorMethod<[], Array<[string, ExternalBlob]>>,
  'recordExists' : ActorMethod<[string, [] | [string]], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'uploadFileAndGetReference' : ActorMethod<
    [ExternalBlob, string, boolean],
    string
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];